# Generated by Django 3.2.16 on 2023-01-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='DateOfBirth',
            field=models.DateField(default=False),
        ),
    ]
