# Generated by Django 3.2.16 on 2023-01-12 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_alter_customuser_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='DateOfBirth',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='manage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
