# Generated by Django 3.2.16 on 2023-01-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0005_alter_customuser_uploadphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='amount',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
