# Generated by Django 3.2.16 on 2023-01-13 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0006_tasklist_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 16, 58, 54, 904987)),
        ),
    ]
