# Generated by Django 3.2.16 on 2023-01-18 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0007_tasklist_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobileno', models.IntegerField()),
                ('ChooseDate', models.DateField(default=datetime.datetime(2023, 1, 18, 11, 28, 5, 909206))),
            ],
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 11, 28, 5, 901205)),
        ),
    ]
