# Generated by Django 3.2.16 on 2023-01-18 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0010_auto_20230118_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_call',
            name='ChooseDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 12, 53, 46, 948784)),
        ),
    ]
