# Generated by Django 3.2.16 on 2023-01-18 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0011_auto_20230118_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 18, 59, 59, 244224)),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task',
            field=models.CharField(choices=[(1, 'Gold'), (2, 'Stocks'), (3, 'Bonds'), (4, 'Mutual Funds')], default=2, max_length=150),
        ),
    ]
