# Generated by Django 3.2.16 on 2023-01-18 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0012_auto_20230118_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 19, 24, 35, 226336)),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Stocks', 'Stocks'), ('Bonds', 'Bonds'), ('Mutual Funds', 'Mutual Funds')], default='Mutual Funds', max_length=150),
        ),
    ]
