# Generated by Django 3.2.16 on 2023-01-19 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0013_auto_20230118_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_call',
            name='MobileNo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 19, 22, 9, 676201)),
        ),
    ]
